### ISSUE TITLE
ID1 : BUG : Deposit page :: The calculated value is shown in the "Income" field When only "Deposit Ammount" field filled in

### ISSUE THREAD

**Issue by Lalily77** [Lalily77/web.test#3]
**Preconditions:**
Login to Callculator app
User: test
Password: newyork1

**Steps to reproduce:**
1. Go to the Deposit page
2. Start filling in the "Deposit Ammount" field with valid data (ex:12345)
3. Verify the "Income" field

**Actual Result:**
The calculated value is shown in the "Income" field
[Video](https://drive.google.com/file/d/1M4TuZfW9GxW4t_gOi8GCy_4ui35AZAGs/view?usp=sharing)

**Expected Result:**
Value for  "Income" field calculated only after all fields filled in

**Comment by varajan** [comment]
Fixed
