### ISSUE TITLE
ID2 : BUG : Deposit page :: May month goes before April month in the Month dropdown list 

### ISSUE THREAD

**Issue by Lalily77** [Lalily77/web.test#4]
**Preconditions:**
Login to Callculator app
User: test
Password: newyork1

**Steps to reproduce:**
1. Go to the Deposit page
2. Click on the Month dropdown
3. Verify the dropdown list

**Actual Result:**
[Attachment](https://drive.google.com/file/d/1ZG9-05mjDQwYA4ZXJJ9FVsaX1llgNuks/view?usp=sharing)
May month goes before April month in the Month dropdown list:
January	
February
March
**_May_**
April	
June
July
August
September
October	
November
December
**Expected Result:**
April month goes before May month in the Month dropdown list:
January	
February
March
April
May	
June
July
August
September
October	
November
December

**Comment by varajan** [comment]
Fixed
