### ISSUE TITLE
ID3 : BUG : Deposit page :: "interest earned" field name starts with a small letter And field is not left aligned

### ISSUE THREAD

**Issue by Lalily77** [Lalily77/web.test#5]
**Preconditions:**
Login to Callculator app
User: test
Password: newyork1

**Steps to reproduce:**
1. Go to the Deposit page
2. Verify the "interest earned" field

**Actual Result:**
Field name starts with a small letter And field is not left aligned
[Attachment](https://drive.google.com/file/d/1KwjV0iLqpy64OMKx3VW-gYu5NDGMuzZK/view?usp=sharing)

**Expected Result:**
Field name starts with a capital letter And field is left aligned
[Attachment](https://drive.google.com/file/d/1bo8YKCtPaatZsjQMPoeyNljdFDtERikt/view?usp=sharing)

**Comment by varajan** [comment]
Fixed
