### ISSUE TITLE
ID4 : BUG : Deposit page :: "end date" field name starts with a small letter

### ISSUE THREAD

**Issue by Lalily77** [Lalily77/web.test#6]
**Preconditions:**
Login to Callculator app
User: test
Password: newyork1

**Steps to reproduce:**
1. Go to the Deposit page
2. Verify the "end date" field

**Actual Result:**
Field name starts with a small letter 
[Attachment](https://drive.google.com/file/d/1RaLvqOx8BHfIy7xI9ZT7YXgbk4izIMTr/view?usp=sharing)

**Expected Result:**
Field name starts with a capital letter
[Attachment](https://drive.google.com/file/d/1Hh_pb7fzzbXLL-LA_vg5n-NNW2mGh17k/view?usp=sharing)

**Comment by varajan** [comment]
Fixed
