### ISSUE TITLE
ID5 : BUG : Deposit page ::  Misspelling "Deposit Ammount" field name 

### ISSUE THREAD

**Issue by Lalily77** [Lalily77/web.test#7]
**Preconditions:**
Login to Callculator app
User: test
Password: newyork1

**Steps to reproduce:**
1. Go to the Deposit page
2. Verify the "Deposit Ammount " field

**Actual Result:**
 "Deposit Ammount" field name 
[Attachment](https://drive.google.com/file/d/1tl4XVMt1dK_QmNf7Esvdk0_9LDtS7668/view?usp=sharing)

**Expected Result:**
 "Deposit Amount" field name

**Comment by varajan** [comment]
Fixed
